---
title: "Demo of Shiny and Leaflet in R"
author: "Nick Mader"
date: "July 11, 2016"
output: html_document
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(readxl)
library(magrittr)
```

```{r data_prep, echo = FALSE}
mySchools <- subset(sch_merge,
                    Network == myNetwork)
```

## School 5Essentials Explorer for `r myNetwork` Schools

```{r app, echo=FALSE, fig.width = 7, fig.height = 12}

levelValues <- sort(unique(mySchools$CPS.Performance.Policy.Level))
ui <- shinyUI(fluidPage(
  sidebarLayout(
    sidebarPanel(
      checkboxGroupInput(inputId = "myLevels",
                         label = ("School Levels to Include"),
                         choices = levelValues,
                         select  = levelValues),
      selectInput(inputId = "symbolizeField",
                  label = "Choose 5Essentials Rating to Visualize:",
                  choices = c("Effective Leaders", "Collaborative Teachers", "Supportive Environment", 
                              "Involved Family", "Ambitious Instruction"),
                  selected = "Involved Family"),
      sliderInput(inputId = "minResponse",
                  label = "Minimum Response Rate:",
                  min = 0.0, max = 1.0, value = 0.0, step = 0.05)
    ),
    mainPanel(
      leafletOutput("schMap")
    )
  )
))

server <- function(input, output){
  mySchs <- reactive(subset(mySchools,
                              subset = CPS.Performance.Policy.Level %in% input$myLevels &
                                as.numeric(gsub("%", "", Student.Response.Rate ))/100 >= input$minResponse))
  essentialsLabels <- c("NOT ENOUGH DATA", "VERY WEAK", "WEAK",
                        "NEUTRAL", "STRONG", "VERY STRONG")
  symbField <- reactive(with(mySchs(),
                             factor(get(gsub(" ", "\\.", input$symbolizeField)), 
                                    levels = essentialsLabels)))
  myPalette <- colorFactor(palette = "Blues",
                           domain = essentialsLabels, 
                           ordered = TRUE)

  output$schMap <- renderLeaflet({
    leaflet(mySchs()) %>%
      addProviderTiles("CartoDB.Positron") %>%
      addCircles(lng = ~Longitude, lat = ~Latitude, popup = ~Name.of.School,
                 color = ~myPalette(symbField()), radius = ~Totals/3, stroke = FALSE,
                 opacity = 0.8, fillOpacity = 0.8) %>%
      addLegend(position = "bottomright", pal = myPalette, values = ~symbField(),
                title = input$symbolizeField)

  })
}

shinyApp(ui, server)
```


